// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type Profile struct {
	UserId               string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Location             string               `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Gender               string               `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Profile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Profile) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *Profile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type Post struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Body                 string               `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	PostedAt             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Post) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Post) GetPostedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PostedAt
	}
	return nil
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Posts struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Posts) Reset()         { *m = Posts{} }
func (m *Posts) String() string { return proto.CompactTextString(m) }
func (*Posts) ProtoMessage()    {}
func (*Posts) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *Posts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Posts.Unmarshal(m, b)
}
func (m *Posts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Posts.Marshal(b, m, deterministic)
}
func (m *Posts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Posts.Merge(m, src)
}
func (m *Posts) XXX_Size() int {
	return xxx_messageInfo_Posts.Size(m)
}
func (m *Posts) XXX_DiscardUnknown() {
	xxx_messageInfo_Posts.DiscardUnknown(m)
}

var xxx_messageInfo_Posts proto.InternalMessageInfo

func (m *Posts) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Images struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Images) Reset()         { *m = Images{} }
func (m *Images) String() string { return proto.CompactTextString(m) }
func (*Images) ProtoMessage()    {}
func (*Images) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *Images) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Images.Unmarshal(m, b)
}
func (m *Images) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Images.Marshal(b, m, deterministic)
}
func (m *Images) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Images.Merge(m, src)
}
func (m *Images) XXX_Size() int {
	return xxx_messageInfo_Images.Size(m)
}
func (m *Images) XXX_DiscardUnknown() {
	xxx_messageInfo_Images.DiscardUnknown(m)
}

var xxx_messageInfo_Images proto.InternalMessageInfo

func (m *Images) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type CreateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type PutProfileRequest struct {
	UserId               string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Location             string               `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Gender               string               `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PutProfileRequest) Reset()         { *m = PutProfileRequest{} }
func (m *PutProfileRequest) String() string { return proto.CompactTextString(m) }
func (*PutProfileRequest) ProtoMessage()    {}
func (*PutProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *PutProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutProfileRequest.Unmarshal(m, b)
}
func (m *PutProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutProfileRequest.Marshal(b, m, deterministic)
}
func (m *PutProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutProfileRequest.Merge(m, src)
}
func (m *PutProfileRequest) XXX_Size() int {
	return xxx_messageInfo_PutProfileRequest.Size(m)
}
func (m *PutProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutProfileRequest proto.InternalMessageInfo

func (m *PutProfileRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PutProfileRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PutProfileRequest) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *PutProfileRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *PutProfileRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type ListUserPostsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserPostsRequest) Reset()         { *m = ListUserPostsRequest{} }
func (m *ListUserPostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserPostsRequest) ProtoMessage()    {}
func (*ListUserPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *ListUserPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserPostsRequest.Unmarshal(m, b)
}
func (m *ListUserPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserPostsRequest.Marshal(b, m, deterministic)
}
func (m *ListUserPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserPostsRequest.Merge(m, src)
}
func (m *ListUserPostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserPostsRequest.Size(m)
}
func (m *ListUserPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserPostsRequest proto.InternalMessageInfo

func (m *ListUserPostsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetPostRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

type CreatePostRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Images               *Images  `protobuf:"bytes,4,opt,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreatePostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreatePostRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreatePostRequest) GetImages() *Images {
	if m != nil {
		return m.Images
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Profile)(nil), "pb.Profile")
	proto.RegisterType((*Post)(nil), "pb.Post")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*Posts)(nil), "pb.Posts")
	proto.RegisterType((*Images)(nil), "pb.Images")
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "pb.UpdateUserRequest")
	proto.RegisterType((*PutProfileRequest)(nil), "pb.PutProfileRequest")
	proto.RegisterType((*ListUserPostsRequest)(nil), "pb.ListUserPostsRequest")
	proto.RegisterType((*GetPostRequest)(nil), "pb.GetPostRequest")
	proto.RegisterType((*CreatePostRequest)(nil), "pb.CreatePostRequest")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xdd, 0x7c, 0x4e, 0xa0, 0x52, 0x56, 0xa5, 0x58, 0x46, 0x82, 0xe0, 0x4b, 0x8b, 0x2a,
	0x6c, 0x29, 0xe5, 0xe3, 0xd0, 0x13, 0x54, 0x08, 0x45, 0x02, 0x14, 0x05, 0xca, 0x81, 0x4b, 0xb5,
	0xb6, 0xa7, 0xc9, 0xaa, 0xb1, 0x77, 0xf1, 0x6e, 0x84, 0x22, 0xf1, 0xa3, 0x38, 0xf3, 0x87, 0xf8,
	0x1b, 0x68, 0x77, 0x63, 0xc7, 0x21, 0xad, 0x8a, 0x04, 0x97, 0xde, 0x76, 0x66, 0xde, 0xce, 0xbc,
	0x7d, 0xf3, 0x6c, 0xe8, 0x16, 0x22, 0x09, 0x45, 0xc1, 0x15, 0x27, 0xae, 0x88, 0xfd, 0x47, 0x53,
	0xce, 0xa7, 0x73, 0x8c, 0x4c, 0x26, 0x5e, 0x5c, 0x44, 0x8a, 0x65, 0x28, 0x15, 0xcd, 0x84, 0x05,
	0xf9, 0x0f, 0xfe, 0x04, 0x60, 0x26, 0xd4, 0xd2, 0x16, 0x83, 0xcf, 0xd0, 0x38, 0x93, 0x58, 0x90,
	0x5d, 0x70, 0x59, 0xea, 0x39, 0x03, 0xe7, 0xb0, 0x3b, 0x71, 0x59, 0x4a, 0xf6, 0xa0, 0x89, 0x19,
	0x65, 0x73, 0xcf, 0x35, 0x29, 0x1b, 0x10, 0x02, 0x8d, 0x9c, 0x66, 0xe8, 0xed, 0x98, 0xa4, 0x39,
	0x6b, 0x24, 0xcb, 0xe8, 0x14, 0xbd, 0x86, 0x45, 0x9a, 0x20, 0xf8, 0xe1, 0x40, 0x7b, 0x5c, 0xf0,
	0x0b, 0x36, 0x47, 0x72, 0x1f, 0xda, 0x0b, 0x89, 0xc5, 0x79, 0x35, 0xa0, 0xa5, 0xc3, 0x51, 0x4a,
	0x06, 0xd0, 0x4b, 0x51, 0x26, 0x05, 0x13, 0x8a, 0xf1, 0x7c, 0x35, 0xaa, 0x9e, 0x22, 0x2f, 0xa0,
	0x13, 0xb3, 0x42, 0xcd, 0x52, 0xba, 0x34, 0x43, 0x7b, 0x43, 0x3f, 0xb4, 0xcf, 0x09, 0xcb, 0xe7,
	0x84, 0x9f, 0xca, 0xf7, 0x4e, 0x2a, 0x2c, 0xf1, 0xa1, 0x33, 0xe7, 0x09, 0x35, 0x6d, 0x2d, 0xaf,
	0x2a, 0x26, 0xfb, 0xd0, 0x9a, 0x62, 0x9e, 0x62, 0xe1, 0x35, 0x2d, 0x1b, 0x1b, 0x05, 0xdf, 0xa1,
	0x31, 0xe6, 0x52, 0x6d, 0x49, 0x51, 0xa3, 0xef, 0x6e, 0xd0, 0x27, 0xd0, 0x88, 0x79, 0xba, 0x2c,
	0xd5, 0xd0, 0x67, 0xf2, 0x12, 0xba, 0x82, 0x4b, 0x85, 0xe9, 0x39, 0x55, 0x66, 0xf2, 0x0d, 0x8c,
	0x2d, 0xf8, 0x95, 0x0a, 0x8e, 0xa0, 0x39, 0xd2, 0xca, 0x6d, 0x8d, 0x2f, 0x35, 0x77, 0xd7, 0x9a,
	0x07, 0x07, 0xd0, 0xd4, 0x54, 0x25, 0x79, 0x08, 0x4d, 0xdd, 0x41, 0x7a, 0xce, 0x60, 0xe7, 0xb0,
	0x37, 0xec, 0x84, 0x22, 0x0e, 0x75, 0x65, 0x62, 0xd3, 0xc1, 0x11, 0xb4, 0x4c, 0x57, 0x49, 0x1e,
	0x43, 0xcb, 0x6c, 0xa6, 0x84, 0x76, 0x35, 0xd4, 0xd4, 0x26, 0xab, 0x42, 0xf0, 0x1e, 0xfa, 0xa7,
	0x05, 0x52, 0x85, 0xda, 0x11, 0x13, 0xfc, 0xba, 0xc0, 0x2b, 0xd4, 0xf8, 0x6b, 0x63, 0x04, 0x09,
	0xf4, 0xcf, 0x44, 0xfa, 0xbf, 0xda, 0x5d, 0xe3, 0xb3, 0x9f, 0x0e, 0xf4, 0xc7, 0x0b, 0xb5, 0xb2,
	0x5a, 0x39, 0xe5, 0x96, 0x38, 0x2e, 0x82, 0xbd, 0x77, 0x4c, 0x2a, 0xad, 0x8f, 0x59, 0xe7, 0x4d,
	0xf4, 0x83, 0x27, 0xb0, 0xfb, 0x16, 0x95, 0x59, 0xf0, 0x1a, 0xaa, 0x37, 0x5d, 0x83, 0xea, 0x70,
	0x94, 0x06, 0xaa, 0x5c, 0x66, 0x1d, 0xfd, 0x4f, 0xd6, 0x0e, 0x2a, 0x07, 0x59, 0x5f, 0x43, 0xe5,
	0x20, 0x59, 0x5a, 0x68, 0xf8, 0xcb, 0x81, 0x3b, 0xea, 0x1b, 0x53, 0x0a, 0x8b, 0xd3, 0x39, 0xcf,
	0x91, 0x9c, 0x00, 0xac, 0x3d, 0x45, 0xee, 0xe9, 0x2b, 0x5b, 0x1e, 0xf3, 0xf7, 0xb7, 0x14, 0x7e,
	0xa3, 0x7f, 0x51, 0xe4, 0x19, 0xdc, 0xdd, 0xd0, 0x87, 0x78, 0xfa, 0xfe, 0x55, 0x92, 0xf9, 0xdd,
	0xd2, 0xf9, 0x92, 0x1c, 0x40, 0x7b, 0x25, 0x12, 0x21, 0x3a, 0xbb, 0xa9, 0x98, 0x5f, 0x7d, 0x23,
	0x6b, 0x6e, 0x26, 0xaa, 0x71, 0xab, 0xc3, 0xaf, 0xe1, 0xf6, 0xfa, 0xf9, 0x97, 0xe3, 0x29, 0x53,
	0xb3, 0x45, 0x1c, 0x26, 0x3c, 0x8b, 0x3e, 0xce, 0x58, 0xae, 0xe8, 0x07, 0x7a, 0x49, 0x33, 0x8c,
	0x56, 0x02, 0x3c, 0x4d, 0xb4, 0x02, 0x51, 0x4c, 0x93, 0x4b, 0xcc, 0xd3, 0x48, 0xc4, 0x27, 0x22,
	0x8e, 0x5b, 0xa6, 0xcd, 0xf1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xb1, 0xba, 0x2e, 0xc5,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TwitterCloneClient is the client API for TwitterClone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TwitterCloneClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	//rpc UpdateUser(UpdateUserRequest) returns (User);
	//rpc PutProfile(PutProfileRequest) returns (Profile);
	ListUserPosts(ctx context.Context, in *ListUserPostsRequest, opts ...grpc.CallOption) (*Posts, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error)
	//rpc GetPostImages(GetPostRequest) returns (Images);
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type twitterCloneClient struct {
	cc *grpc.ClientConn
}

func NewTwitterCloneClient(cc *grpc.ClientConn) TwitterCloneClient {
	return &twitterCloneClient{cc}
}

func (c *twitterCloneClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.twitterClone/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterCloneClient) ListUserPosts(ctx context.Context, in *ListUserPostsRequest, opts ...grpc.CallOption) (*Posts, error) {
	out := new(Posts)
	err := c.cc.Invoke(ctx, "/pb.twitterClone/ListUserPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterCloneClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.twitterClone/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterCloneClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.twitterClone/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwitterCloneServer is the server API for TwitterClone service.
type TwitterCloneServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*empty.Empty, error)
	//rpc UpdateUser(UpdateUserRequest) returns (User);
	//rpc PutProfile(PutProfileRequest) returns (Profile);
	ListUserPosts(context.Context, *ListUserPostsRequest) (*Posts, error)
	GetPost(context.Context, *GetPostRequest) (*Post, error)
	//rpc GetPostImages(GetPostRequest) returns (Images);
	CreatePost(context.Context, *CreatePostRequest) (*empty.Empty, error)
}

// UnimplementedTwitterCloneServer can be embedded to have forward compatible implementations.
type UnimplementedTwitterCloneServer struct {
}

func (*UnimplementedTwitterCloneServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedTwitterCloneServer) ListUserPosts(ctx context.Context, req *ListUserPostsRequest) (*Posts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserPosts not implemented")
}
func (*UnimplementedTwitterCloneServer) GetPost(ctx context.Context, req *GetPostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedTwitterCloneServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}

func RegisterTwitterCloneServer(s *grpc.Server, srv TwitterCloneServer) {
	s.RegisterService(&_TwitterClone_serviceDesc, srv)
}

func _TwitterClone_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterCloneServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.twitterClone/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterCloneServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterClone_ListUserPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterCloneServer).ListUserPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.twitterClone/ListUserPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterCloneServer).ListUserPosts(ctx, req.(*ListUserPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterClone_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterCloneServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.twitterClone/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterCloneServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterClone_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterCloneServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.twitterClone/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterCloneServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TwitterClone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.twitterClone",
	HandlerType: (*TwitterCloneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _TwitterClone_CreateUser_Handler,
		},
		{
			MethodName: "ListUserPosts",
			Handler:    _TwitterClone_ListUserPosts_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _TwitterClone_GetPost_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _TwitterClone_CreatePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
